using FrostHelper.Helpers;
using FrostHelper.SessionExpressions;
using System.Diagnostics.CodeAnalysis;
using System.Reflection.Emit;
using OpCodes = System.Reflection.Emit.OpCodes;

namespace FrostHelper.API;

// [ModExportName("FrostHelper")] - defined in API.cs
public static partial class API {
    /// <summary>
    /// Creates a delegate which can evaluate a Session Expression efficiently.
    /// This is the recommended way to evaluate session expressions.
    /// This function should only be called once when creating an entity, the delegate should be stored for re-use.
    /// Added in Frost Helper 1.81.0
    /// </summary>
    /// <param name="str">The expression</param>
    /// <param name="context">The Session Expression Context to use, leave null to use the global context. The context object should be generated by <see cref="CreateSessionExpressionContextV2"/>.</param>
    /// <param name="returnType">The type that should be returned by the expression.</param>
    /// <returns>A delegate which evaluates the expression. Will always be of type Func{Session, object?, returnType} and can safely be cast to that type.</returns>
    public static Delegate? CreateTypedSessionExpressionOrNull(string str, object? context, Type returnType) {
        if (ConditionHelper.TryCreate(str, AssertIsOrNull<IExpressionContext>(context) ?? ExpressionContext.Default, out var expr)) {
            var compiled = CompiledCondition.GetDelegateFor(expr, returnType);
            return compiled;
        }

        return null;
    }

    /// <summary>
    /// Coerces the given value to the target type, using Session Expression rules.
    /// Added in Frost Helper 1.81.0
    /// </summary>
    public static object CoerceValueInSessionExpression(object value, Type targetType) {
        return ConditionHelper.Condition.Coerce(value, targetType);
    }
    
    /// <summary>
    /// Creates an object which can evaluate a Session Expression.
    /// The returned object can be passed to GetSessionExpressionValue and other similar methods.
    ///
    /// It is recommended to use CreateTypedSessionExpressionOrNull to create a typed delegate instead.
    /// </summary>
    public static bool TryCreateSessionExpression(string str, [NotNullWhen(true)] out object? expression) {
        return TryCreateSessionExpression(str, ExpressionContext.Default, out expression);
    }
    
    /// <summary>
    /// Creates an object which can evaluate a Session Expression, using the given Session Expression Context.
    /// The context object should be generated by <see cref="CreateSessionExpressionContextV2"/>.
    /// The returned object can be passed to GetSessionExpressionValue and other similar methods.
    /// 
    /// It is recommended to use CreateTypedSessionExpressionOrNull to create a typed delegate instead.
    /// </summary>
    public static bool TryCreateSessionExpression(string str, object? context, [NotNullWhen(true)] out object? expression) {
        if (ConditionHelper.TryCreate(str, AssertIsOrNull<IExpressionContext>(context) ?? ExpressionContext.Default, out var expr)) {
            expression = CompiledCondition<object>.GetFor(expr);
            return true;
        }

        expression = null;
        return false;
    }

    /// <summary>
    /// Returns the current value of a Session Expression.
    /// The object passed as the 1st argument needs to be created via <see cref="TryCreateSessionExpression(string, object, out object?)"/>
    /// </summary>
    public static object GetSessionExpressionValue(object expression, Session session)
        => AssertExpression(expression).Get(session, userdata: null);
    
    /// <summary>
    /// Returns the current value of a Session Expression with the given userdata, which can be any arbitrary object,
    /// passed to custom commands defined by the Session Expression Context used when creating the Session Expression.
    /// The object passed as the 1st argument needs to be created via <see cref="TryCreateSessionExpression(string, object, out object?)"/>
    /// </summary>
    public static object GetSessionExpressionValue(object expression, Session session, object? userdata)
        => AssertExpression(expression).Get(session, userdata);
    
    /// <summary>
    /// Returns the type that the given session expression will return, or typeof(object) if that's unknown.
    /// The object passed as the 1st argument needs to be created via <see cref="TryCreateSessionExpression(string, object, out object?)"/>
    /// </summary>
    public static Type GetSessionExpressionReturnedType(object expression) {
        var expr = AssertExpression(expression);

        return expr.SourceCondition.ReturnType ?? typeof(object);
    }
    
    /// <summary>
    /// Returns the current value of a Session Expression as an integer, coercing it if needed.
    /// The object passed as the 1st argument needs to be created via <see cref="TryCreateSessionExpression(string, object, out object?)"/>
    /// </summary>
    public static int GetIntSessionExpressionValue(object expression, Session session)
        => AssertExpression(expression).GetOther<int>(session, userdata: null);
    public static int GetIntSessionExpressionValue(object expression, Session session, object? userdata)
        => AssertExpression(expression).GetOther<int>(session, userdata);
    
    /// <summary>
    /// Returns the current value of a Session Expression as a float, coercing it if needed.
    /// The object passed as the 1st argument needs to be created via <see cref="TryCreateSessionExpression(string, object, out object?)"/>
    /// </summary>
    public static float GetFloatSessionExpressionValue(object expression, Session session)
        => AssertExpression(expression).GetOther<float>(session, userdata: null);
    public static float GetFloatSessionExpressionValue(object expression, Session session, object? userdata)
        => AssertExpression(expression).GetOther<float>(session, userdata);
    
    /// <summary>
    /// Returns the current value of a Session Expression as a boolean, coercing it if needed.
    /// The object passed as the 1st argument needs to be created via <see cref="TryCreateSessionExpression(string, object, out object?)"/>
    /// </summary>
    public static bool GetBoolSessionExpressionValue(object expression, Session session)
        => AssertExpression(expression).GetOther<bool>(session, null);
    public static bool GetBoolSessionExpressionValue(object expression, Session session, object? userdata)
        => AssertExpression(expression).GetOther<bool>(session, userdata);

    /// <summary>
    /// Registers a simple Session Expression command, which will be accessible in Session Expressions via
    /// - $cmdName if a context is provided,
    /// - $modName.cmdName if the command is global (no context is provided).
    /// Added in Frost Helper 1.81.0
    /// </summary>
    /// <param name="modName">Name of the mod which registers this command. Will be used to prefix the command name.</param>
    /// <param name="cmdName">Name of the command</param>
    /// <param name="context">The Expression Context, created via CreateSessionExpressionContextV2, to register this command to. Leave null to register the command globally.</param>
    /// <param name="command">
    /// Function called each time the command needs to be evaluated. Must have a return type.
    /// May accept up to 2 arguments, where the first one is a Session, and the second is userdata.
    /// Userdata is object? by default, it can be typed as a different type if the command is registered non-globally.
    /// If userdata is not typed as object?, and the correct userdata type is not passed when evaluating the command, an exception will be thrown.
    ///
    /// For optimal performance, make sure the delegate is created from a static method, like:
    /// <code>
    /// static void Register() {
    ///     RegisterSimpleSessionExpressionCommandV2("yourMod", "three", null, [], Three);
    /// }
    /// 
    /// static int Three() {
    ///    return 3;
    /// }
    /// </code>
    /// </param>
    /// <param name="description">Description of this command, visible in Mapping Utils. (ApiRenderPart is defined in Api.RenderPart.cs)</param>
    public static void RegisterSimpleSessionExpressionCommandV2(string modName, string cmdName, object? context, 
        IReadOnlyList<ApiRenderPart> description, Delegate command) {
        var key = context is null ? $"{modName}.{cmdName}" : cmdName;
        var method = command.Method;

        if (method.ReturnType == typeof(void)) {
            throw new Exception("Simple command delegate must return a value.");
        }

        var desc = new CommandDescriptor {
            Name = key,
            DeclaringMod = modName,
            DeclaringType = null,
            Description = RenderPart.FromApi(description),
            Arguments = [],
            ReturnType = TypeDescriptor.For(method.ReturnType),
        };

        var delegateParameters = command.Method.GetParameters();
        Type? requiredUserdataType = null;
        if (delegateParameters.Length > 2) {
            throw new Exception($"Simple command delegates can only accept up to 2 parameters! '{key}' has '{delegateParameters.Length}' parameters");
        }
        
        if (delegateParameters.Length > 1 && delegateParameters[1].ParameterType != typeof(object)) {
            requiredUserdataType = delegateParameters[1].ParameterType;

            if (!requiredUserdataType.IsClass)
                throw new Exception("Userdata can only be a class.");

            if (context is null) {
                throw new Exception($"Command {key} requires a specific userdata type ({requiredUserdataType}), which is not supported when registering a global command. Provide a custom Expression Context to register the command to, or accept object? as the userdata and handle type mismatches inside your delegate.");
            }
        }

        if (delegateParameters.Length > 0 && delegateParameters[0].ParameterType != typeof(Session)) {
            throw new Exception($"Simple command delegate's first parameter must be of type Session. '{key}' has '{delegateParameters[0].ParameterType}'");
        }
        
        var commandCondition = new ModApiSimpleCommandV2(command, delegateParameters.Length, requiredUserdataType) { Descriptor = desc };
        
        if (AssertIsOrNull<IExpressionContext>(context) is { } ctx) {
            ctx.RegisterSimpleCommand(key, commandCondition);
            return;
        }

        SimpleCommands.Registry[key] = new SimpleCommand(desc, commandCondition);
    }

    /// <summary>
    /// Registers a simple Session Expression function, which will be accessible in Session Expressions via
    /// - $cmdName(...) if a context is provided,
    /// - $modName.cmdName(...) if the command is global (no context is provided).
    /// </summary>
    /// Added in Frost Helper 1.81.0
    /// <param name="modName">Name of the mod which registers this command. Will be used to prefix the command name.</param>
    /// <param name="cmdName">Name of the command</param>
    /// <param name="context">The Expression Context, created via CreateSessionExpressionContextV2, to register this command to. Leave null to register the command globally.</param>
    /// <param name="func">
    /// Function called each time the function needs to be evaluated. Must have a return type.
    /// MUST accept at least 2 arguments, where the first one is a Session, and the second is userdata.
    /// Userdata is object? by default, it can be typed as a different type if the command is registered non-globally.
    /// If userdata is not typed as object?, and the correct userdata type is not passed when evaluating the function, an exception will be thrown.
    ///
    /// The delegate may accept more than 2 arguments, in which case all further arguments will be obtained from the Session Expression.
    /// These arguments may accept any C# type, arguments will be coerced automatically using usual Session Expression rules.
    /// 
    /// For optimal performance, make sure the delegate is created from a static method, like:
    /// <code>
    /// static void Register() {
    ///     RegisterFunctionSessionExpressionCommandV2("yourMod", "sum", null, [], Sum);
    /// }
    /// 
    /// static int Sum(Session session, object? userdata, int a, int b) {
    ///    return a + b;
    /// }
    /// </code>
    /// </param>
    /// <param name="description">Description of this function, visible in Mapping Utils. (ApiRenderPart is defined in Api.RenderPart.cs)</param>
    public static void RegisterFunctionSessionExpressionCommandV2(string modName, string cmdName, object? context, IReadOnlyList<ApiRenderPart> description, Delegate func) {
        var key = context is null ? $"{modName}.{cmdName}" : cmdName;
        var method = func.Method;
        var delegateParameters = method.GetParameters();
        if (delegateParameters.Length < 2) {
            throw new Exception("Function command delegates must have at least two parameters: Session, userdata");
        }

        if (delegateParameters[0].ParameterType != typeof(Session)) {
            throw new Exception("Function command delegates' first argument must be Session");
        }
        
        Type? requiredUserdataType = null;
        if (delegateParameters[1].ParameterType != typeof(object)) {
            requiredUserdataType = delegateParameters[1].ParameterType;

            if (!requiredUserdataType.IsClass)
                throw new Exception("Userdata can only be a class.");

            if (context is null) {
                throw new Exception($"Function {key} requires a specific userdata type ({requiredUserdataType}), which is not supported when registering a global command. Provide a custom Expression Context to register the command to, or accept object? as the userdata and handle type mismatches inside your delegate.");
            }
        }
        
        var desc = new CommandDescriptor {
            Name = key,
            DeclaringMod = modName,
            ReturnType = TypeDescriptor.For(method.ReturnType),
            Arguments = delegateParameters.Skip(2).Select(p => new ArgumentDescriptor(p.Name ?? "", TypeDescriptor.For(p.ParameterType))).ToList(),
            DeclaringType = null,
            Description = RenderPart.FromApi(description),
        };
        var cmd = new FunctionCommand(((args, out result, out message) => {
            if (args.Count != desc.Arguments.Count) {
                message = $"Function {desc.Name} requires {desc.Arguments.Count} arguments, received {args.Count}";
                result = null;
                return false;
            }
            
            result = new ModFunctionConditionV2(args, func, delegateParameters, requiredUserdataType);
            result.Descriptor = desc;
            message = null;
            return true;
        }), desc);
        
        if (AssertIsOrNull<IExpressionContext>(context) is { } ctx) {
            ctx.RegisterFunctionCommand(key, cmd);
            return;
        }

        FunctionCommands.Registry[key] = cmd;
    }

    /// <summary>
    /// Creates a Session Expression Context object, which can be passed to <see cref="TryCreateSessionExpression(string,object,out object?)"/>
    /// This allows you to register custom commands for specific entities.
    /// A context should be created once, and reused as much as possible.
    ///
    /// Commands and functions can be added to this context via other API functions.
    /// Added in Frost Helper 1.81.0
    /// </summary>
    public static object CreateSessionExpressionContextV2() {
        return new ExpressionContext([], []);
    }
    
    #region Obsolete
    /// <summary>
    /// Creates a Session Expression Context object, which can be passed to <see cref="TryCreateSessionExpression(string,object,out object?)"/>
    /// This allows you to register custom commands for specific entities.
    /// A context should be created once, and reused as much as possible.
    /// <br />
    /// Do not capture entity instances into the Func objects, instead pass a `userdata` object when calling GetSessionExpressionValue,
    /// which will be passed as the 2nd argument your functions.
    /// <br />
    /// Dictionary keys are names under which the commands will be available. For example, if your key is 'coolValue',
    /// then it will be accessed as `$coolValue` in Session Expressions created using this context.
    /// </summary>
    [Obsolete("Use CreateSessionExpressionContextV2 instead, combined with RegisterSimpleSessionExpressionCommandV2. Obsolete since 1.81.0")]
    public static object CreateSessionExpressionContext(
        Dictionary<string, Func<Session, object? /* userdata */, object>>? simpleCommands,
        Dictionary<string, Func<Session, object? /* userdata */, IReadOnlyList<object>, object>>? functionCommands) {
        
        return new ExpressionContext(
            (simpleCommands ?? []).ToDictionary(kv => kv.Key, kv => SimpleCommands.CreateCommandFromModFunc(kv.Value)),
            (functionCommands ?? []).ToDictionary(kv => kv.Key, kv => new FunctionCommand(
                FunctionCommands.CreateFactoryForCustomCommand(kv.Value), 
                new CommandDescriptor {
                    Name = kv.Key,
                    ReturnType = TypeDescriptor.Any
                })));
    }
    
    /// <summary>
    /// Registers a simple Session Expression command, which will be accessible via $modName.cmdName in Session Expressions.
    /// </summary>
    /// <param name="modName">Name of the mod which registers this command. Will be used to prefix the command name.</param>
    /// <param name="cmdName">Name of the command</param>
    /// <param name="func">Function called each time the command needs to be evaluated</param>
    [Obsolete("Use RegisterSimpleSessionExpressionCommandV2 instead. Obsolete since 1.81.0")]
    public static void RegisterSimpleSessionExpressionCommand(string modName, string cmdName, Func<Session, object> func) {
        RegisterSimpleSessionExpressionCommandV2(modName, cmdName, null, [], func);
    }
    
    /// <summary>
    /// Registers a Session Expression function, which will be accessible via $modName.cmdName in Session Expressions.
    /// </summary>
    /// <param name="modName">Name of the mod which registers this command. Will be used to prefix the command name.</param>
    /// <param name="cmdName">Name of the command</param>
    /// <param name="func">Function called each time the function needs to be evaluated.
    /// 2nd argument contains a list of the values of all arguments to the function.
    /// </param>
    [Obsolete("Use RegisterFunctionSessionExpressionCommandV2 instead. Obsolete since 1.81.0")]
    public static void RegisterFunctionSessionExpressionCommand(string modName, string cmdName, Func<Session, IReadOnlyList<object>, object> func) {
        FunctionCommands.Register(modName, cmdName, (session, userdata, args) => func(session, args));
    }
    #endregion
    
    #region Impl Details
    // NON-API!
    private static CompiledCondition<object> AssertExpression(object expression) {
        if (expression is not CompiledCondition<object> expr) {
            throw new ArgumentException($"Object '{expression}' is not of type {nameof(ConditionHelper.Condition)}!");
        }

        return expr;
    }
    
    // NON-API!
    private static ExpressionContext AssertContext(object ctx) {
        if (ctx is not ExpressionContext expr) {
            throw new ArgumentException($"Object '{ctx}' is not of type {nameof(ExpressionContext)}!");
        }

        return expr;
    }
    
    // NON-API!
    private static T AssertIs<T>(object ctx) {
        if (ctx is not T expr) {
            throw new ArgumentException($"Object '{ctx}' is not of type {typeof(T)}!");
        }

        return expr;
    }
    
    // NON-API!
    private static T? AssertIsOrNull<T>(object? ctx) where T : class {
        if (ctx is not T expr) {
            if (ctx is null)
                return null;

            throw new ArgumentException($"Object '{ctx}' is not of type {typeof(T)}!");
        }

        return expr;
    }
    
        internal class InvalidUserdataTypeException(Type expected, Type? actual) : Exception {
        public override string Message => $"Userdata type was invalid, expected '{expected}', received '{actual?.Name ?? "null"}'";
    }
    
    private sealed class ModApiSimpleCommandV2(Delegate func, int argCount, Type? requiredUserdataType) : ConditionHelper.Condition {
        private DynamicReferenceCell _cell;
        private object?[]? _args;

        private static readonly MethodInfo ThrowInvalidUserdataExceptionIfNeededMethodInfo
            = typeof(ModApiSimpleCommandV2).GetMethod(nameof(ThrowInvalidUserdataExceptionIfNeeded), BindingFlags.Static | BindingFlags.NonPublic)!;
        
        public override object Get(Session session, object? userdata) {
            _args ??= new object[argCount];
            var args = _args;
            switch (args.Length) {
                case >= 2:
                    if (userdata is null) {
                        if (requiredUserdataType is not null)
                            throw new InvalidUserdataTypeException(requiredUserdataType!, null);
                        args[1] = null;
                        goto case 1; // fallthrough
                    }
                    
                    if (!userdata.GetType().IsAssignableTo(requiredUserdataType)) {
                        throw new InvalidUserdataTypeException(requiredUserdataType!, userdata.GetType());
                    }
                    
                    args[1] = userdata;
                    goto case 1; // fallthrough
                case 1:
                    args[0] = session;
                    break;
            }
            
            var ret = func.DynamicInvoke(_args);
            if (ret is bool b)
                return BoolToBoxedInt(b);
            return ret!;
        }

        internal override void Emit(ConditionCompilationCtx ctx, Type targetType) {
            var method = func.Method;
            if (func.Target is not null) {
                if (_cell != default) {
                    ctx.Il.EmitLoadReference(_cell);
                } else {
                    ctx.Il.EmitNewReference(func.Target, out _cell);
                }
            }

            if (argCount > 0)
                ctx.EmitLoadSession();
            if (argCount > 1) {
                ctx.EmitLoadUserdata();
                if (requiredUserdataType is not null) {
                    ctx.Il.Emit(OpCodes.Call, ThrowInvalidUserdataExceptionIfNeededMethodInfo.MakeGenericMethod(requiredUserdataType));
                }
            }
            ctx.Il.Emit(OpCodes.Call, method);
            ctx.EmitConvertTo(method.ReturnType, targetType);
        }

        private static TUserdata ThrowInvalidUserdataExceptionIfNeeded<TUserdata>(object? userdata) {
            if (userdata is not TUserdata cast)
                throw new InvalidUserdataTypeException(typeof(TUserdata), userdata?.GetType());

            return cast;
        }

        internal override bool UsesCurrentConditionLocalInEmit => false;

        protected internal override Type ReturnType => Descriptor!.ReturnType.CSharpType;

        protected override IEnumerable<object> GetArgsForDebugPrint() => [func];
    }
    
    private sealed class ModFunctionConditionV2(IReadOnlyList<ConditionHelper.Condition> args, Delegate func, ParameterInfo[] parameterInfos, Type? requiredUserdataType) 
        : FunctionCommands.FunctionCondition(args) {
        
        private DynamicReferenceCell _cell;
        
        private readonly object?[] _array = new object[args.Count + 2];
        private ConditionHelper.Condition GetArg(int index) => args[index];

        private static readonly MethodInfo MethodGetArg =
            typeof(ModFunctionConditionV2).GetMethod(nameof(GetArg), BindingFlags.Instance | BindingFlags.NonPublic)!;
        
        private static readonly MethodInfo ThrowInvalidUserdataExceptionIfNeededMethodInfo
            = typeof(ModApiSimpleCommandV2).GetMethod(nameof(ThrowInvalidUserdataExceptionIfNeeded), BindingFlags.Static | BindingFlags.NonPublic)!;
        
        public override object Get(Session session, object? userdata) {
            var arr = _array;
            arr[0] = session;
            if (userdata is null) {
                if (requiredUserdataType is not null)
                    throw new InvalidUserdataTypeException(requiredUserdataType!, null);
            } else if (!userdata.GetType().IsAssignableTo(requiredUserdataType)) {
                throw new InvalidUserdataTypeException(requiredUserdataType!, userdata.GetType());
            }
            arr[1] = userdata;

            for (int i = 0; i < args.Count; i++) {
                arr[i + 2] = Coerce(args[i].Get(session, userdata), parameterInfos[i + 2].ParameterType);
            }
            
            return func.DynamicInvoke(_array)!;
        }

        protected internal override Type ReturnType { get; } = func.Method.ReturnType;

        internal override void Emit(ConditionCompilationCtx ctx, Type targetType) {
            var il = ctx.Il;
            var method = func.Method;
            LocalBuilder? tempOrigCond = null;
            
            if (func.Target is not null) {
                if (_cell != default) {
                    ctx.Il.EmitLoadReference(_cell);
                } else {
                    ctx.Il.EmitNewReference(func.Target, out _cell);
                }
            }
            if (parameterInfos.Length > 0)
                ctx.EmitLoadSession();
            if (parameterInfos.Length > 1) {
                ctx.EmitLoadUserdata();
                if (requiredUserdataType is not null) {
                    ctx.Il.Emit(OpCodes.Call, ThrowInvalidUserdataExceptionIfNeededMethodInfo.MakeGenericMethod(requiredUserdataType));
                }
            }
            
            var i = 0;
            foreach (var arg in args) {
                var parameterInfo = parameterInfos[i + 2];
                il.EmitSwapOutCurrentCondition(ref tempOrigCond, ctx, arg, () => {
                    il.Emit(OpCodes.Ldloc, tempOrigCond!);
                    il.Emit(OpCodes.Ldc_I4, i);
                    il.Emit(OpCodes.Call, MethodGetArg);
                });
                arg.Emit(ctx, parameterInfo.ParameterType);
                i++;
            }
            
            il.EmitRevertCurrentCondition(tempOrigCond, ctx);
            
            ctx.Il.Emit(OpCodes.Call, method);
            ctx.EmitConvertTo(method.ReturnType, targetType);
        }

        internal override bool UsesCurrentConditionLocalInEmit => args.Any(a => a.UsesCurrentConditionLocalInEmit);
        
        private static TUserdata ThrowInvalidUserdataExceptionIfNeeded<TUserdata>(object? userdata) {
            if (userdata is not TUserdata cast)
                throw new InvalidUserdataTypeException(typeof(TUserdata), userdata?.GetType());

            return cast;
        }
    }
    #endregion
}